-- GENERATED by build-products.js — edit the CSVs, not this file.
-- Product names match the Stripe Payment Link names in payment_links.csv exactly.
-- Safe to re-run. On an existing database, run migrations.sql first.
DELETE FROM order_items WHERE product_id IN (SELECT id FROM products);
DELETE FROM products;
ALTER SEQUENCE products_id_seq RESTART WITH 1;

INSERT INTO products (name, category, price, description, payment_link)
VALUES
('Gentle Eye Makeup Remover - 130 mL', 'skin', 46.00, 'A gentle eye-area cleanser designed to remove makeup and everyday impurities without leaving the delicate skin feeling stripped.', NULL),
('Gentle Cleansing Gel - 200 mL', 'skin', 67.00, 'A refreshing gel cleanser for daily use that helps remove makeup, excess oil and surface impurities while leaving skin feeling clean and comfortable.', NULL),
('Daily Facial Cleanser - 200 mL', 'skin', 67.00, 'An everyday facial cleanser that lifts away dirt, oil and makeup to leave the complexion feeling fresh, soft and balanced.', NULL),
('C2O Cream to Oil Cleanser - 200 mL', 'skin', 67.00, 'A nourishing cream cleanser that transforms into an oil-like texture to dissolve makeup, sunscreen and impurities while supporting a soft skin feel.', NULL),
('Daily Exfoliating Facial Scrub - 200 mL', 'skin', 67.00, 'A facial exfoliant that helps polish away dead surface cells and smooth rough texture for a fresher, more refined-looking complexion.', NULL),
('ASAP Hand Sanitiser - 110 mL', 'general', 12.50, 'A convenient hand sanitiser for quick cleansing when soap and water are unavailable, ideal for handbags, workspaces and travel.', 'https://buy.stripe.com/00w28lgfP0DP2FtdrEd3i0E'),
('Deluxe Facial Cloth', 'skin', 19.00, 'A soft, reusable facial cloth designed to assist with thorough cleanser removal and gentle daily cleansing.', 'https://buy.stripe.com/aFa00d6Ffbit0xldrEd3i0D'),
('Liquid Platinum - 130 mL', 'skin', 82.00, 'An overnight resurfacing treatment that helps refine the appearance of skin texture and promote a smoother, brighter-looking complexion.', 'https://buy.stripe.com/aFa28le7H9algwjafsd3i0C'),
('N20 Peptide Complex - 30 mL', 'skin', 190.00, 'A concentrated peptide serum formulated to support firmer-looking, smoother and more resilient skin.', 'https://buy.stripe.com/6oU4gt7Jjaep93R73gd3i0B'),
('Super A+ Serum - 30 mL', 'skin', 125.00, 'A vitamin A-focused night serum that helps improve the look of uneven texture, fine lines and overall skin clarity.', 'https://buy.stripe.com/bJebIVgfP4U53Jx2N0d3i0A'),
('Super B Complex - 30 mL', 'skin', 125.00, 'A hydrating vitamin B serum that helps support the skin barrier, improve moisture retention and calm the look of stressed skin.', 'https://buy.stripe.com/aFa14he7HgCN1Bp9bod3i0z'),
('Super C+ Complex - 30 mL', 'skin', 125.00, 'An antioxidant vitamin C serum that helps brighten dull-looking skin and support a more even, radiant complexion.', 'https://buy.stripe.com/5kQfZb0gRbiteob87kd3i0y'),
('Clear Complexion Gel - 50 mL', 'skin', 68.00, 'A lightweight treatment gel for blemish-prone skin that helps reduce the look of congestion, excess oil and visible breakouts.', 'https://buy.stripe.com/00w14hfbLbitgwjdrEd3i0x'),
('Radiance Serum - 30 mL', 'skin', 125.00, 'A brightening serum designed to improve the appearance of dullness, uneven tone and discolouration for a more luminous look.', 'https://buy.stripe.com/fZu6oBbZzcmx4NBevId3i0w'),
('DNA Renewal Treatment - 30 mL', 'skin', 170.00, 'An advanced anti-ageing treatment formulated to support smoother, firmer-looking skin and improve the appearance of visible ageing.', 'https://buy.stripe.com/8x23cpe7Hcmx93R2N0d3i0v'),
('Firming Eye Lift - 15 mL', 'skin', 115.00, 'A targeted eye treatment that hydrates and helps improve the appearance of fine lines, puffiness and tired-looking skin around the eyes.', 'https://buy.stripe.com/cNi3cpe7H9al93R1IWd3i0u'),
('Advanced Hydrating Moisturiser - 50 mL', 'skin', 114.00, 'A daily moisturiser that provides lasting hydration and helps leave the skin feeling soft, supple and comfortably nourished.', 'https://buy.stripe.com/7sYcMZaVv0DP93RfzMd3i0t'),
('Ultimate Hydration - 50 mL', 'skin', 114.00, 'A rich hydrating treatment for dry or dehydrated skin that helps restore moisture and improve softness and comfort.', 'https://buy.stripe.com/4gM5kx7Jj1HTeob5Zcd3i0r'),
('Hydrating Night Repair+ - 50 mL', 'skin', 104.00, 'A nourishing overnight moisturiser that supports skin recovery while helping improve hydration, smoothness and softness by morning.', 'https://buy.stripe.com/9B6bIV0gRbitdk7drEd3i0q'),
('SPF50+ Moisturising Defence+ - 100 mL', 'skin', 95.00, 'A high-protection facial sunscreen with moisturising benefits, designed for comfortable daily wear and broad-spectrum UV protection.', 'https://buy.stripe.com/5kQaER2oZ1HTfsfgDQd3i0p'),
('SPF50+ Ultimate Defence - 100 mL', 'skin', 95.00, 'A lightweight, high-protection facial sunscreen designed to provide broad-spectrum UV defence for everyday use.', 'https://buy.stripe.com/dRmaER8Nn9al5RFdrEd3i0o'),
('CC Correcting Cream SPF15 - 75 mL', 'skin', 72.00, 'A colour-correcting complexion cream that helps even the look of skin tone, soften visible redness and provide light daily coverage.', 'https://buy.stripe.com/14A7sF3t39alcg34V8d3i0n'),
('Soothing Gel - 200 mL', 'skin', 65.00, 'A cooling, lightweight gel that helps comfort and hydrate skin after sun exposure, hair removal or professional treatments.', 'https://buy.stripe.com/4gM28lgfPeuFcg3bjwd3i0m'),
('Hydra Plump Lip Balm - 10 mL', 'skin', 26.00, 'A conditioning lip balm that helps hydrate, soften and smooth dry lips while giving them a naturally plumped appearance.', 'https://buy.stripe.com/dRm28l2oZeuFdk7cnAd3i0l'),
('Revitalising Bodyscrub - 200 mL', 'skin', 60.00, 'A body exfoliant that helps remove dry surface cells and smooth rough areas, leaving skin feeling polished and refreshed.', 'https://buy.stripe.com/3cI00dd3D0DP6VJdrEd3i0k'),
('Revitalising Bodymoist - 200 mL', 'skin', 60.00, 'A daily body moisturiser that replenishes hydration and leaves the skin feeling soft, smooth and nourished.', 'https://buy.stripe.com/4gMaER1kVdqB2FtevId3i0j'),
('Clearskin Bodygel - 120 mL', 'skin', 80.00, 'A lightweight body treatment gel for areas prone to congestion and breakouts, helping improve the look of blemishes and uneven texture.', 'https://buy.stripe.com/28E00d8NndqBbbZbjwd3i0i'),
('Gentle Cleansing Gel - 50 mL', 'skin', 37.50, 'A travel-size refreshing gel cleanser that removes makeup, excess oil and impurities while leaving skin feeling clean and comfortable.', 'https://buy.stripe.com/7sY28lbZzcmx7ZNdrEd3i0h'),
('Daily Facial Cleanser - 50 mL', 'skin', 37.50, 'A travel-size everyday cleanser that lifts away dirt, oil and makeup to leave skin feeling fresh and balanced.', 'https://buy.stripe.com/bJe9AN1kVeuFfsfbjwd3i0g'),
('C2O Cream to Oil Cleanser - 50 mL', 'skin', 37.50, 'A travel-size nourishing cream-to-oil cleanser that dissolves makeup, sunscreen and impurities without a tight after-feel.', 'https://buy.stripe.com/00w5kx2oZ3Q1cg33R4d3i0f'),
('Daily Exfoliating Facial Scrub - 50 mL', 'skin', 37.50, 'A travel-size facial exfoliant that helps smooth rough texture and remove dull surface cells for fresher-looking skin.', 'https://buy.stripe.com/8x28wJ2oZ1HT1Bp73gd3i0e'),
('SPF50+ Moisturising Defence+ - 50 mL', 'skin', 58.00, 'A compact high-protection facial sunscreen with moisturising benefits, ideal for daily use and travel.', 'https://buy.stripe.com/6oU8wJgfP1HTeobcnAd3i0d'),
('SPF50+ Ultimate Defence - 50 mL', 'skin', 58.00, 'A compact lightweight facial sunscreen that provides high broad-spectrum UV protection for everyday wear.', 'https://buy.stripe.com/aFaaERfbL9alcg3afsd3i0c'),
('Soothing Gel - 50 mL', 'skin', 37.50, 'A travel-size cooling gel that helps hydrate and comfort skin after sun exposure, hair removal or professional treatments.', 'https://buy.stripe.com/fZueV7aVvdqBbbZafsd3i0b'),
('Discovery Set', 'skin', 145.00, 'A curated introductory skincare set featuring complementary essentials for customers beginning a new routine or trying the range.', 'https://buy.stripe.com/3cI6oB6Ff72d1Bp0ESd3i0a'),
('Healthy Skin Essentials', 'skin', 129.00, 'A practical collection of everyday skincare essentials selected to cleanse, hydrate and protect the skin.', 'https://buy.stripe.com/7sYcMZfbLbita7V4V8d3i09'),
('Clear Complexion', 'skin', 149.00, 'A targeted routine for oily, congested or blemish-prone skin, designed to support a clearer and more balanced-looking complexion.', 'https://buy.stripe.com/9B67sFd3Dbit1Bp5Zcd3i08'),
('Radiance Routine', 'skin', 249.00, 'A complete brightening routine designed to improve the look of dullness, uneven tone and overall skin radiance.', 'https://buy.stripe.com/14A6oB2oZfyJa7VcnAd3i07'),
('Post Treatment Kit', 'skin', 99.00, 'A gentle aftercare collection created to cleanse, soothe, hydrate and protect skin following suitable professional treatments.', 'https://buy.stripe.com/7sYfZb1kV5Y9a7VdrEd3i06'),
('Signature Serum Collection', 'skin', 315.00, 'A premium serum collection combining complementary formulas to address hydration, brightness and visible signs of ageing.', 'https://buy.stripe.com/fZuaER8Nn2LX3Jx9bod3i05'),
('Brow Gel', 'brow', 35.00, 'A styling gel that shapes, defines and holds brow hairs in place for a neat, polished finish.', 'https://buy.stripe.com/00w6oBfbL3Q1gwjevId3i03'),
('Brow & Lash Serum', 'brow', 45.00, 'A conditioning serum designed to nourish the appearance of brows and lashes and support a fuller, healthier-looking finish.', 'https://buy.stripe.com/28E00dd3D2LXeob0ESd3i04'),
('Eyebrow Powder', 'brow', 25.00, 'A blendable brow powder that fills sparse areas and adds soft, natural-looking definition with buildable colour.', 'https://buy.stripe.com/5kQeV77Jjcmx2FtcnAd3i02'),
('Eyebrow Brush', 'brow', 10.00, 'A precision brow brush designed for shaping, blending and applying brow powder or other brow products.', 'https://buy.stripe.com/9B67sF9RreuFeobfzMd3i01'),
('Eyelash Growth Mascara', 'lash', 50.00, 'A defining mascara with conditioning benefits that enhances the appearance of lash length, volume and fullness.', 'https://buy.stripe.com/14A8wJ0gR4U54NBfzMd3i00');
